import { useEffect, useState } from "react"
import { useNavigate,useLocation } from "react-router-dom"
import { useForm } from 'react-hook-form';
import "./Signup.css"
import Navbar from '../components/Navbar.jsx'
import { API_URL } from "../API/apiendpoint.js";

const Home = (props) => {
    const {
        register,
        handleSubmit,
        watch,
        formState: { errors, isSubmitting },
    } = useForm()

    const [data, setdata] = useState([])
    const [urlid, seturlid] = useState()
    const [Name, setName] = useState()
    const [Role, setRole] = useState()
    const navigate = useNavigate()
    // const location = useLocation()

    // const uuid = location.state || {}

    const handledata = async () => {
        try {
            
            const response = await fetch(`${API_URL}/url/all`,{
                method: "GET",
                headers: {
                    "Content-Type": "application/json",
                },
                // body : JSON.stringify({uuid}),
                credentials: 'include'
            })
            // console.log(response);
            const res = await response.json()
            if (!(res.status)) {
                alert("Failed to fetch infomation\n",res.message)
                console.log("res : ",res);
                
                navigate("/login")
                return
            }
            // console.log("res : ", res);
            setdata(res.urls)
            setName(res.name)
            setRole(res.role)
            // console.log("data : ", data);
        } catch (error) {
            console.error("something is wrong")
        }

    }

    useEffect(() => {
        handledata()
    }, [])

    // useEffect(() => {
    //     console.log("data : ", data);
    // }, [data]);

    const onSubmit = async (data) => {
        const response = await fetch(`${API_URL}/url`, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify({data}),
            credentials: 'include',
        })
        const res = await response.json()
        console.log("res : ",res);
        
        if (!(res.status)) {
            let msg = "Couldn't add data to database"
            seturlid(msg)
            return
        }
        let msg = `${import.meta.env.FRONTEND_URL}/${API_URL}/${res.shorturl}`
        seturlid(msg)
        return
    }



    return (
        <>
        <Navbar btnval1 = {props.btnval1} btnval2 = {props.btnval2} />
        <div className = "maindivformain">
            <div className="generate">
                {Name && <h2>Welcome {Name.toUpperCase()} !</h2>}<br/>
                <h2>Wanna generate your Short URL 😉...</h2><br />
                <div className="form_d">
                    <form action="" method="post" onSubmit={handleSubmit(onSubmit)}>
                        <input type="text" placeholder="Enter a valid URL : (https://example.com)" {...register('url', {
                            required: 'URL is required',
                            pattern: {
                                value: /^(https?:\/\/[^\s$.?#].[^\s]*)$/,
                                message: 'Invalid URL format'
                            }
                        })} />
                        <div className="errors">
                            {errors.url && errors.url.message}
                        </div>
                        <button type="submit">Generate</button>
                    </form>
                </div>
            </div>
            {urlid && (<div className="url-generated">
                URL Generated : <strong>{urlid}</strong>
            </div>)}
            {data.length != 0 && (<div className="table">
            {Role == "ADMIN"? <div>
                <h2>Hello Admin {Name} </h2>
                <h2>You have the access to view All URLs generated by existing Users 🤫</h2>
                </div>
            :
                <h2>The URLs generated by you 🤗</h2>
            }
                <table>
                    <thead>
                        <tr>
                            <th>Sl No.</th>
                            <th>Short URL</th>
                            <th>Short ID</th>
                            <th>Redirect Link</th>
                            <th>Clicks</th>
                            <th>Created By</th>
                        </tr>
                    </thead>
                    <tbody>
                        {data.map((url, index) => (
                            <tr key={url._id}>
                                <td>{index + 1}</td>
                                <td>{API_URL}/{url.shortID}</td>
                                <td>{url.shortID}</td>
                                <td>{url.redirectUrl}</td>
                                <td>{url.visited.length}</td>
                                <td>{url.createdUser}</td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
            )}
        </div>
        </>
    )
}

export default Home
